version: '3.8'
services:
  playwright-test:
    image: playwright-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run mern-jobify-chrome
    volumes:
      - ./playwright/playwright-report/:/app/playwright-report
      - ./playwright/test-results/:/app/test-results
